### ISSUE TITLE
DATABASE_URL: Required

### ISSUE THREAD

**Issue by giulianok** [cfortuner/promptable#17]
Following the **Examples** instructions, I get the following error when running `pnpm dev` 

https://github.com/cfortuner/promptable#examples

```
web:dev: ❌ Invalid environment variables:
web:dev:  DATABASE_URL: Required
web:dev:
web:dev: error - Failed to load next.config.mjs, see more info here https://nextjs.org/docs/messages/next-config-error
web:dev: Error: Invalid environment variables
web:dev:     at file:///Users/giulianomini/Projects/Testing/promptable/apps/web/src/env/server.mjs:16:9
web:dev:     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
web:dev:     at async Promise.all (index 0)
web:dev:     at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
web:dev:     at async file:///Users/giulianomini/Projects/Testing/promptable/apps/web/next.config.mjs:6:38
web:dev:  ELIFECYCLE  Command failed with exit code 1.
web:dev: ERROR: command finished with error: command (/Users/giulianomini/Projects/Testing/promptable/apps/web) pnpm run dev exited (1)
promptable:dev: CLI Building entry: src/index.ts
promptable:dev:  ELIFECYCLE  Command failed.
docs:dev:  ELIFECYCLE  Command failed.
gpt-react-query:dev:  ELIFECYCLE  Command failed.
promptable:dev:  ELIFECYCLE  Command failed.
command (/Users/giulianomini/Projects/Testing/promptable/apps/web) pnpm run dev exited (1)
```

**Comment by justinliang1020** [comment]
To fix this, copy the contents of [.env.example ](https://github.com/cfortuner/promptable/blob/main/apps/web/.env.example) into a new file, .env, in the same directory.

**Comment by cfortuner** [comment]
Sorry about this @giulianok . I'l leave this open until we simplify this

**Comment by giulianok** [comment]
> Sorry about this @giulianok . I'l leave this open until we simplify this

let me know if help is needed

**Comment by cfortuner** [comment]
@giulianok Yeah! want to join the discord? Plenty of ways to improve htis stuff :)
