### ISSUE TITLE
Setting "\n" for stop causes failure

### ISSUE THREAD

**Issue by austintackaberry** [cfortuner/promptable#36]
```
SyntaxError: Unexpected token
in JSON at position 1
at JSON.parse (<anonymous>)
at unescapeStopTokens (/usr/src/app/node_modules/.pnpm/promptable@0.0.10/node_modules/promptable/dist/index.js:644:17)
 at OpenAI.generate (/usr/src/app/node_modules/.pnpm/promptable@0.0.10/node_modules/promptable/dist/index.js:688:24)
 at runCompletion (/usr/src/app/dist/src/lib/promptable.js:13:33)
 at runIsScheduleRequest (/usr/src/app/dist/src/lib/promptable.js:29:23)
 at /usr/src/app/dist/app.js:98:83
 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

```
"promptable": "^0.0.10"
```

**Comment by cfortuner** [comment]
Thanks for reporting. Will take a look today
